### PR TITLE
Update `Polish`

### PR DESCRIPTION
**Pull request by GucekPL**

### CODE REVIEW

**Comment by anddea** [comment]
Please remove the part that says `\watching -> views`. It was my mistake and because of that the setting won't work. I'll fix it only in the next 24 hours. 

Also, it should be reverted, your input -> views, not views -> your input. 

You can test this setting in order to understand how it works. You should put there the actual words for views count that goes under video.

**Comment by Kuddus73** [comment]
> It was my mistake and because of that the setting won't work. I'll fix it only in the next 24 hours.

To avoid confusion, I'll translate the new strings once you've fixed it, so let me know once you've done that.

**Comment by GucekPL** [comment]
> To avoid confusion, I'll translate the new strings once you've fixed it, so let me know once you've done that.

I will do same

**Comment by Kuddus73** [comment]
@anddea Need a clarification:
_Examples:
English: 10K views = K -> 1000, views -> views
Spanish: 10K vistas = K -> 1000, vistas -> views_

**Isn't 10K equal to 10000 and not _1000_?**

**Comment by anddea** [comment]
K is a prefix for a kilo which is 1000. So it means 10K is 10 * 1000 = 10,000. That's why I also call it multiplier. 

It would be easy if all languages had the same prefixes and metrics, there would be no need to adjust this setting for each langauge.

**Comment by Kuddus73** [comment]
> It would be easy if all languages had the same prefixes and metrics, there would be no need to adjust this setting for each langauge.

Yeah about that, how should I translate the "_10K views = K -> 1000_" part in Italian?
Because as you can see from the screenshots it gets tricky:
**English**
Screenshot_20240328_064112_YouTube
**Italian**
Screenshot_20240328_064022_YouTube

**Comment by GucekPL** [comment]
@anddea Please check that I have fixed it correctly. At the moment I don't have time to test this function

**Comment by anddea** [comment]
@GucekPL @Kuddus73 I updated strings, you can translate now.

Please note, that this string is functional, so you have to specify just like it's shown in your language. That's why I recommend to check first. I can merge this PR now and when you test it, you can fix this translation.
```xml
<string name="revanced_hide_video_with_low_view_num_multiplier_value">K -> 1 000\nM -> 1 000 000\nB -> 1 000 000 000\nviews -> views</string>
```

### Italian
For example, as I know Italian in YouTube doesn't show thousands in views, it's not 10K views, it's 10.000 visualizzazioni. So you don't have to specify `K -> 1 000` as there's no need in that. You have to specify only what you see in your language.

And for million there's a 10 Mio di visualizzazioni should be 
`Mio di -> 1 000 000\nvisualizzazioni -> views` 
or 
`Mio -> 1 000 000\ndi? visualizzazioni -> views` 
whatever you like you the most. And don't forget about billion as well.

### Polish
I just checked Polish, and it shows tys. as 1000, mln as 1 000 000, wyświetleń as views, so it should be:
`tys. -> 1000\nmln -> 1000000\nwyświetleń -> views` and also whatever it is for billion views.

If you have any suggestions how I can make it user-friendly, so everyone can understand, let me know. Though if you translate it now correctly, there will be no need to open this setting ever again.

**Comment by GucekPL** [comment]
ohhh, I understand this now, take me a moment and I will translate strings now properly 😅

**Comment by GucekPL** [comment]
Now it should be all good

**Comment by Kuddus73** [comment]
@anddea Seems clear now.

But at least in English (didn't try with other languages), the line `n\views -> views` doesn't seem to be required as it hides videos even without the line.
Hiding videos with less than 5M views:

https://github.com/anddea/revanced-patches/assets/127908708/bb00575d-774e-4f89-9426-f4a9e15c7a4a

**So just wanted to ask if it is an intended behaviour or a bug.**

**Comment by anddea** [comment]
@Kuddus73 views key is needed, because it can accidentally match other patterns. For example uploaded date. You might think that you're hiding a video with 5 views but you're accidentally hiding a video with 10 views just because it says "Channel name • 10 views • 5 days ago". 5 days will match the pattern because there's no word for views. But for English it'll work, because it's harcoded, if there's no specified views key for your language, then it will use word "views" for all languages. So even if you don't put views for your language it will use "views" and it won't hide any video in your language just because views is not found for your language but it is crucial, so it protects you from hiding videos uploaded 5 days ago instead of 5 views.

**Comment by anddea** [comment]
I tried to clarify a little more, so I changed some strings a little @GucekPL 

```xml
<string name="revanced_hide_video_with_low_view_num_multiplier_summary">Specify your language template for the number of views under each video in the user interface. Each key (a letter/word in your language) -> value (meaning of the key) must be on a new line. Keys go before "->" sign. If you switch app or system language you have to reset this setting.\n\nExamples:\nEnglish: 10K views = K -> 1000, views -> views\nSpanish: 10 K vistas = K -> 1000, vistas -> views</string>
<string name="revanced_hide_video_with_low_view_old_summary">"[Old] Hide videos with less than 1,000 views exposed to the home feed.
Some videos, including those from channels you subscribe to, may not be hidden even if they have fewer than 1,000 views.

It's an old version, if you're using option above, you don't need to use this one."</string>
```

**Comment by GucekPL** [comment]
I've never translated one string so much time in my life hahaha, sure, I'll replace it, take me a moment, and thanks a lot for your patience and explaining how the function works

**Comment by anddea** [comment]
> I've never translated one string so much time in my life

Sorry 😅. It's just I'm not sure how to explain it in a better way. But your translations are life-saving for other people from your country(ies), especially this functional string that should be specified correctly, they won't need to change anything, just put the number and that's it.

**Pull request merged**
