### PR TITLE
feat(YouTube - Translations): Update Korean

### PR DESCRIPTION
**Pull request by zerozero0022**
feat(YouTube - Translations): Update Korean

match full word
mute button

### CODE REVIEW

**Comment by anddea** [comment]
Thank you for your contribution

**Comment by zerozero0022** [comment]
I was worried if I should fix it separately because there were a lot of translations before it was fixed in Dev.14, but I'm glad it was fixed in Dev.15. 

And thank you for developing app.

**Comment by zerozero0022** [comment]
I don't know exactly how to translate 'match full word' into Korean, could you please create Summary_on&off?

**Comment by anddea** [comment]
To be honest, I don't see if this summary is any more helpful. It might suggest that you can use multiple-word keywords and it will filter out occurrences of both words separately, but it won't. The only difference is that it checks for word boundaries; if there are any spaces (if match full word is enabled).

**Pull request merged**
