### PR TITLE
feat(YouTube - Translations): Update `Polish`

### PR DESCRIPTION
**Pull request by GucekPL**
Updated strings

### CODE REVIEW

**Comment by GucekPL** [comment]
@anddea why have I conflicts? I don't understand why

**Comment by anddea** [comment]
Strings are updated, you should merge upstream (my dev branch) to your Dev branch and resolve conflicts. I can resolve conflicts when I'll merge it, it will add me as co-author.

**Comment by GucekPL** [comment]
NOOOO I DON'T WANT CLOSE

**Comment by anddea** [comment]
If you synced and overrode it, then yes. It's gone. It's better to create new branch from Dev branch and open PR from there, so if you sync your commits are still there in your own branch. 

You can try to run this command if you know hash of HEAD commit before sync. 
```
git branch -f my_branch original_commit_hash
```

**Comment by GucekPL** [comment]
> If you synced and overrode it, then yes. It's gone. It's better to create new branch from Dev branch and open PR from there, so if you sync your commits are still there in your own branch. 
> 
> You can try to run this command if you know hash of HEAD commit before sync. 
> ```
> git branch -f dev original_commit_hash
> ```

@anddea Today I have nothing interesting to do, so I will translate all strings from 2.224.0 again, and if it will be any problem again, I will leave the rest to you, so that I don't do anything wrong again

**Pull request closed without merging**
