### PR TITLE
feat(YouTube - Settings): Add custom name for Extended preference

### PR DESCRIPTION
**Pull request by Francesco146**
Add support for #377 

ps: for a first time it was cool. what an experience!

### CODE REVIEW

**Comment by anddea** [comment]
Check these lines

https://github.com/anddea/revanced-patches/blob/56cc1af1b9d2d8ba6654217108c4ecddcbc21525/src/main/kotlin/app/revanced/patches/youtube/utils/settings/ResourceUtils.kt#L117-L120

It would be more dynamic to pass it there and assign title in line 120. But this way you'll have to add one more argument and additional check. 

Now, the title for the setting is set by dynamic string - @sting/revanced_extended... For every language it might differ. And you change only one strings.xml file by overwriting that string. So it won't apply for other languages.

**Comment by Francesco146** [comment]
> https://github.com/anddea/revanced-patches/blob/56cc1af1b9d2d8ba6654217108c4ecddcbc21525/src/main/kotlin/app/revanced/patches/youtube/utils/settings/ResourceUtils.kt#L117-L120
> 

so, something like this?

```kotlin
fun ResourceContext.addReVancedPreference(key: String, insertKey: String, customTitle: String? = null) {
    //...
    setAttribute("android:title", customTitle == null ? "@string/revanced_${key}_title" : customTitle)
    //...
```

> Now, the title for the setting is set by dynamic string - @string/revanced_extended... For every language it might differ. And you change only one strings.xml file by overwriting that string. 

not sure if the whole idea of a custom name need a translation.

> So it won't apply for other languages.

**Comment by anddea** [comment]
Yes, something like this. Check if everything works fine. 

Custom title doesn't need translation, it's just if you add custom title to default string file it won't be visible if someone uses different language, they won't see that custom title.

**Comment by Francesco146** [comment]
> Yes, something like this. 

great, what about the other xml file? the only place you access it is here:

https://github.com/anddea/revanced-patches/blob/56cc1af1b9d2d8ba6654217108c4ecddcbc21525/src/main/kotlin/app/revanced/patches/youtube/utils/settings/ResourceUtils.kt#L168-L179

> if you add custom title to default string file it won't be visible

so there's no `revanced_extended_settings_title`? did I get it right?

**Comment by anddea** [comment]
Although, there are just 2 languages that has this setting changed. But it's a good practice to set it dynamically. 

https://github.com/search?q=repo%3Aanddea%2Frevanced-patches+ReVanced_extended_settings_titl+path%3A%2F%5Esrc%5C%2Fmain%5C%2Fresources%5C%2Fyoutube%5C%2Ftranslations%5C%2F%2F&type=code

**Comment by Francesco146** [comment]
> Although, there are just 2 languages that has this setting changed. But it's a good practice to set it dynamically.

alright! tomorrow I'll push the first fix for values-v21.xml. I'm out of options for revanced_settings_with_toolbar.xml

https://github.com/anddea/revanced-patches/blob/56cc1af1b9d2d8ba6654217108c4ecddcbc21525/src/main/resources/youtube/settings/layout/revanced_settings_with_toolbar.xml#L24

**Comment by anddea** [comment]
After copying the xml file in your aforementioned piece of code, you can add xml editing and replace if custom name is set to something other than "revanced_extended_settings_title"

And then this
```xml
app:title="@string/revanced_extended_settings_title"
```

should be (which is language independent, because we don't need localization for Custom Name, anyone can set whatever they want)
```xml
app:title="Custom Name"
```

**Comment by Francesco146** [comment]
thanks! finally i understand what's the general idea is!

**Comment by Francesco146** [comment]
@anddea i managed to edit `revanced_settings_with_toolbar.xml`, now `app:title` is set up correctly, however the in values-v21 (and in the other two xml files that modifies it) the value of `revanced_extended_settings_title` doesn't change. and it doesn't change because the function `ResourceContext.addReVancedPreference()` isn't called for these files.

how can i edit it dynamically as you say? i would keep editing the values.xml files that edit `revanced_extended_settings_title`

**Comment by Francesco146** [comment]
```kotlin
arrayOf("", "-ru-rRU", "-uk-rUA").forEach { valuefile ->
    context.xmlEditor["res/values$valuefile-v21/strings.xml"].use { editor ->
        with(editor.file) {
            val nodeList = getElementsByTagName("string")

            for (i in 0 until nodeList.length) {
                val node: Node = nodeList.item(i)
                if (node.attributes.getNamedItem("name").nodeValue != "revanced_extended_settings_title")
                    continue
                node.textContent = CustomName
                break
            }
        }
    }
}
```

do you have any other suggestions?

**Comment by anddea** [comment]
There must be something wrong that is difficult to determine at a glance. You can debug this by printing each value to see if you have selected the item correctly. If you use println(), it will be printed during the patching process. 

You should also specify the CustomName on line 194. And later you will need to implement the check, if CustomName is the default one, you do not need to change anything, so that it can be retrieved from strings.xml (for each localization), but this one is easy.

**Comment by Francesco146** [comment]
I'll implement the thing that doesn't change the name if it's equal to the default valule. do you know where that toolbar title is set up? i thought it was here:

https://github.com/anddea/revanced-patches/blob/56cc1af1b9d2d8ba6654217108c4ecddcbc21525/src/main/resources/youtube/settings/layout/revanced_settings_with_toolbar.xml#L24

but it isn't.

**Comment by anddea** [comment]
It should be that exact place where toolbar title is set. When patching there is a folder for temporary files, go there and find this file, then check if this line is not changed. 

To make it easier you can just search in IDE for the file name (in InteliJ IDEA and Android Studio - Shift Ctrl O / Shift Cmd O).

Maybe when you try to edit it, it's not there yet, or maybe you specified something wrong in the code, that's why printing variables, directories, grabbed node and attribute will help you to understand.

**Comment by Francesco146** [comment]
that's the neat part! in my IDE, the file located in:

temporary-directory-patcher/patched/res/layout/revanced_settings_with_toolbar.xml

shows:
```xml
    app:title="prova uno due"\>
```

it appears that it doesn't affect the toolbar title that I've sent you via the screenshot.

**Comment by anddea** [comment]
https://github.com/anddea/revanced-integrations/blob/dev/app/src/main/java/com/google/android/apps/youtube/app/settings/videoquality/VideoQualitySettingsActivity.java

**Comment by Francesco146** [comment]
l'll leave this that way for now, if there is a better way, I can't figure it out at least today. i don't know how to work with the integrations (when its code get executed? from who? how does it affects the patches? how can i debug it since it's an apk? afaik intellij doesn't support this kind of interactions). 

@anddea thanks for the kind advices you gave me! they were pretty usefull for figuring out that some xml values files are not available from the start and the `close()` function can be use for these type of files

**Comment by anddea** [comment]
If there's no better solution for now, I think you can just edit strings.xml files, and delete everything other than that, including passing argument to add preference function, because once you edit the end XML file where the title is retrieved from, it becomes useless to pass argument, because it'll be changed in xml anyway.

**Comment by Francesco146** [comment]
@anddea i've done, a different approch might be what inotia00 used for applying the translations. loop through all languages, for each xml values file, see if it has changed the value of `revanced_extended_settings_title`, if yes, add this xml file to the list of files to modify. 

i was just now implementing this reasoning, but i am finding difficulty accessing the xml files. the `SettingPatch` is using `AbstractSettingsResourcePatch(“youtube/settings”)`, which prevents me from accessing the resources via `classLoader.getResources(“youtube/translations/$language/strings.xml”)`. do you have any advice on this?

**Comment by anddea** [comment]
You need context of resources here, doesn't it work in execute? Although, passing context to function is not a good idea, it's not passed as expected. I think it's better to run it without additional function and you can create arrayOf or setOf for language folders and do forEach on that array to run xml editor to minimize redundancy.

**Comment by Francesco146** [comment]
> You need context of resources here, doesn't it work in execute? 

not with my concept. some values files are not copied during the `execute()` function. i wanted to create this forEach languages in the `close()` function, when all the values file have been copied. do you know how can i get the context of the translations in that function? maybe through the classLoader? idk

> Although, passing context to function is not a good idea, it's not passed as expected.

oh ok, for the sake of curiosity, what happens that is not expected? i created the function locally so it wouldn't be an issue, but I'll follow the best practices!

**Comment by anddea** [comment]
I'll check later what can we do here.

**Comment by Francesco146** [comment]
@anddea i did it! what do you think?

**Comment by anddea** [comment]
Looks good, I can't test it myself now though, but I can merge it if you tested it and it works as expected. It's the dev branch anyway.

**Comment by Francesco146** [comment]
> Looks good, I can't test it myself now though, but I can merge it if you tested it and it works as expected. It's the dev branch anyway.

I've tested it, works good! let's see if in the next pre-release some users will find some bugs

**Comment by hilmiiz** [comment]
[patch_log.txt](https://github.com/anddea/revanced-patches/files/15188458/patch_log.txt)

I face this error after changing custom name

**Comment by hilmiiz** [comment]
Screenshot_2024-05-02-20-48-10-836_com termux

Will getting error even i remove "d". Or any tutorial to change this?

**Comment by hilmiiz** [comment]
> @hilmiiz open a new issue and provide the details there

How? I don't know how to use GitHub. In your device, u can change the settings name?

**Comment by Francesco146** [comment]
@hilmiiz here:

[OPEN NEW - Bug Report](https://github.com/anddea/revanced-patches/issues/new?assignees=&labels=Bug+report&projects=&template=bug-report.yml&title=bug%3A+)

**Pull request merged**
