### PR TITLE
feat(YouTube - SettingElement): Note in description

### PR DESCRIPTION
**Pull request by odkate**
Screenshot_20240413-171500
Screenshot_20240413-171400

### CODE REVIEW

**Comment by anddea** [comment]
I think this warning should be after first sentence. 

I'll add a fallback method to use "About" if key is not found. 
I think it would be better to use something more formal, "do not write..." seems a little off. 

What about "parent settings"? Does it work?

**Comment by anddea** [comment]
It's the hardest part, to come up with a good name and description. It should be similar to "tuck away preferences" description. Maybe something like "account and your data will be ignored", or "are not available", because they will be ignored when I fix it anyway, so it will be as a note, and not a recommendation what to do. 

Also, you have to escape double quotes with a backslash because we already use double quotes as description value, otherwise it will consider the end of description and will raise an error: \"Account\".

**Comment by anddea** [comment]
It shouldn't matter if you have "parent settings", because it puts above that option even if it's not available, maybe it will actually work for "Account" and "Your data" too, I'll test myself later.

**Comment by anddea** [comment]
It shouldn't matter if you have "parent settings", because it puts above that option even if it's not available, maybe it will actually work for "Account" and "Your data" too, I'll test myself later.

**Comment by odkate** [comment]
> It should be similar to "tuck away preferences" description

Replaced by

**Comment by odkate** [comment]
> parent settings

Screenshot_20240413-224411

**Comment by anddea** [comment]
Yes, that's the right place. So probably it's available for "account" and "your data" too. I'll test it next week. Then there will be no need for this note/warning at all.

**Comment by odkate** [comment]
> account" and "your data

Currently, they are loss if Parent settings is injected👆🏻

**Comment by odkate** [comment]
@anddea with "Autoplay" are also lost
Screenshot_20240414-132845

**Comment by anddea** [comment]
You mean "account" and "your data"? They are not available until you wait for new interface to load (if you clean install the app). If you use old version or spoof to old version then you won't see them.

**Comment by odkate** [comment]
> old version

Yes, I use 18.25.40, I already realized that this version simply does not have these items in the settings

**Comment by anddea** [comment]
This should work now if you specify "Account" or "Your data", so there's no need for this note now. If you face any issues let me know.

**Pull request closed without merging**
