### PR TITLE
feat(YouTube - Translations): Update Korean

### PR DESCRIPTION
**Pull request by zerozero0022**
feat(YouTube - Translations): Update Korean

revanced_alt_thumbnail_alternative_domain

### CODE REVIEW

**Comment by zerozero0022** [comment]
check 'spoof client' switch & dialog.

**Comment by anddea** [comment]
What do you mean?

**Comment by zerozero0022** [comment]
After enabling "Spoof Client", a dialog (turning off ...) is displayed.

If the default value is "off"...
I think "turning on this setting cause various side effect of spoofing client" would be correct.

but revanced and rvx defaults it to on.

**Comment by anddea** [comment]
I turned this off by default because a lot of people still don't have buffering issues and side effects of spoof client are very bad to be enabled by default. 

Do you mean that message for turning off should appear when you turn off that option, not when you turn on? But does it matter? It makes sense in both cases.

**Pull request merged**
