### PR TITLE
feat(YouTube - Translations): Update Korean

### PR DESCRIPTION
**Pull request by zerozero0022**
feat(YouTube - Translations): Update Korean

### CODE REVIEW

**Comment by zerozero0022** [comment]
so...
if your build is merged with the inotia build, it's okay to write problems on using filtering keywords in Korean in the information section?

korean issue on 'match full word'
On - compound keywords that contain filter keyword but may have different meanings may be filtered out 

Off - words with postposition may not be filtered out
example:
english - in youtube
korean translation - 유튜브에서 (에서: postpostion)]

**Comment by anddea** [comment]
Tbh, I couldn't understand, if I enter this word "유튜브에서", it works in both cases with on and off. Could you elaborate? Maybe screenshots? 

I noticed, that if I sync inotia translation strings now, it reverts back translation, it should be updated there as well, because strings will  be overwritten after next merge.

**Comment by zerozero0022** [comment]
Because Korean and English have different sentence structures, it lets korean user know that unwanted words (thumbnails) may appear.
You don't need to fix it.
I'll just put explanation about it in the About section.

**Comment by anddea** [comment]
I don't understand what to fix actually. But you can add that info in "About keyword filtering", it seems the right place.

**Comment by zerozero0022** [comment]
okay. thanks

**Comment by zerozero0022** [comment]
Screenshot_20240724-121208_YouTube~01

**Comment by zerozero0022** [comment]
sorry

patch names and patch descriptions displayed in revanced manager are difficult to translate unless someone forks a ReVanced(inotia, anddea) GitHub, translates and modifies the names and descriptions in patch java files to another language, and redistributes the patch files, right?

**Pull request merged**
