### PR TITLE
feat(YouTube - Translations): Update `Japanese`

### PR DESCRIPTION
**Pull request by riolove1**

### CODE REVIEW

**Comment by riolove1** [comment]
> You can just open PR to inotia's repo and ask him to merge it as an exception for this time, but later it will be easier just to go to his crowdin and update strings there visually.
> 
> Also, may I ask, why did you add `crowdin.yml`? I'm gonna delete it, and then I'll merge it.

Sorry for the inconvenience. I was just setting up sync between Crowdin and GitHub, and I'm not used to it yet, so this happened.

**Comment by anddea** [comment]
During updating and removing unused strings, your translation could be overwritten by the one from inotia's crowdin. That's why I suggest you to contribute your translations there.

**Comment by anddea** [comment]
But I can revert back if needed, just tell me. But I'm saying to contribute there, because my automated script gets translations from there and replaces old strings, so next time translations are updated there it will be overwritten again.

**Comment by riolove1** [comment]
Understood. From now on, I will translate directly in crowdin on inotia instead of making pull requests.

**Comment by riolove1** [comment]
By the way, did you know that inotia crowdin has been shut down? It has now been moved to ReX crowdin.

**Comment by riolove1** [comment]
> During updating and removing unused strings, your translation could be overwritten by the one from inotia's crowdin. That's why I suggest you to contribute your translations there.

Hello, Inotia crowdin is back and I've finished all the translation work.

**Comment by anddea** [comment]
Okay, once he accepts transaltions into his repo, it'll be here as well.

**Pull request merged**
