### PR TITLE
feat(YouTube - Translations): Update `Italian`

### PR DESCRIPTION
**Pull request by Kuddus73**
Updates Italian translations.

### CODE REVIEW

**Comment by anddea** [comment]
There's one missing string.

```xml
<string name="sb_submit_failed_timeout">Unable to submit segments (API timed out).</string>
```

**Comment by anddea** [comment]
Btw, I fixed for you, but if you'd like to know, all apostrophes and double quotes inside should be escaped with backslash like this. But you don't have to worry about that because I'll fix it anyway. 

```xml
<string>Can\'t solve \"this issue\"</string>
```
Unless you're using them for multiline string like
```xml
<string>"Multiline
string"</string>
```

**Comment by Kuddus73** [comment]
> all apostrophes and double quotes inside should be escaped with backslash like this.

Thanks, didn't know.

> There's one missing string.
> 
> ```
> <string name="sb_submit_failed_timeout">Unable to submit segments (API timed out).</string>
> ```

I just checked and that string is already translated in the Italian strings.xml (**line 1083**).

**Comment by anddea** [comment]
Yes, you're right, script detected it wrong, because there was no closing tag for this string:

```xml
<string name="sb_submit_failed_rate_limit">Can\'t submit the segment.\nRate Limited (too many from the same user or IP).</string>
```
Because the string on the line 1082 is continued on 1085. But I already fixed tit.

**Pull request merged**
