### PR TITLE
feat(YT Music - Translations): Update Korean

### PR DESCRIPTION
**Pull request by zerozero0022**
feat(YT Music - Translations): Update Korean

### CODE REVIEW

**Comment by anddea** [comment]
If you contribute to inotia's crowdin and once he adds translations to his repository, they will be translated here too automatically. Unless automated script will give some unknown error and skip.

**Comment by zerozero0022** [comment]
okay thanks

**Comment by zerozero0022** [comment]
Simply put, you did the inotia github fork, and you import translation files from Github, right?

**Comment by anddea** [comment]
No, only unique strings. They should be in missing strings file but there can be some strings from crowdin just by an accident, so if you already translated those exact keys then just delete them, they will be automatically merged from crowdin.

**Comment by zerozero0022** [comment]
https://github.com/anddea/revanced-patches/commit/85cf0c016a20b4fb67c0a7aa1176fdce87d3ad48

I can't request for this setting to inotia because I think it's something you'll be upset about because you're the developer of this setting.

I'm sorry, but could you please request for this setting you made to inotia?

**Comment by anddea** [comment]
> you'll be upset about

Why should I be? I don't think he accepts feature requests for YouTube though. 

> feat(YouTube - Settings): Add search bar for settings 

Why do you need it there if you have it here? Eventually, I'm going to open PRs for all unique features from this repo, so our repos are synced. Search needs more polishing but I got very busy lately. If @inotia00 is ready to accept as it is right now and if he has time to polish it, then I can open PR right away.

**Pull request closed without merging**
