### PR TITLE
feat(YouTube - Translations): Update Korean

### PR DESCRIPTION
**Pull request by zerozero0022**
add

< string name="gms_core_dialog_dismiss_text">Don\'t show again</string>
< string name="revanced_icon_revancify_yellow">Revancify Yellow</string>
< string name="revanced_gms_show_dialog_title">Show optimization dialog for GMSCore</string>
 < string name="revanced_gms_show_dialog_summary">Displays the optimization dialog for GMSCore at each application startup.</string>

### CODE REVIEW

**Comment by anddea** [comment]
There are also strings for YT Music, will you translate them too?

**Comment by zerozero0022** [comment]
done

**Comment by zerozero0022** [comment]
@anddea 
I have question.
I shouldn't ask you(RVX-anddea) for ReVanced features that are not yet PRs to RVX(inotia), right?

**Comment by anddea** [comment]
The main maintainer is inotia, so when he merges them, they will be here as well. If we could contact each other and discuss with him, maybe it'd be faster.

**Comment by zerozero0022** [comment]
I'd like to request this feature, but...
if this feature is created, will there be more app start popups or more overlay buttons? I ask in the comments because it's unlikely.

Spoof client dialog
- Like GmsCore dialog, when disabled, ask on every app startup, press ok to go to spoof client page (with 'dont show again' button)
- This feature is disabled, so first time users may not realize it.

• Background playback overlay button
can start background playback immediately by pressing the overlay button without disabling PIP or pressing the headset button on the PIP player.

**Comment by anddea** [comment]
I think it'll be a lot of dialogs on startup, currently on clean install, we have app restart dialog, GmsCore background and GmsCore don't kill my app dialog, plus YT:s own dialog to select account. 

Overlay buttons take a lot of space already, not sure if it's a good thing for UX. Plus I always consider for features that already exist, no matter if takes additionals steps, if you can do that. With more features we increase the hardness of maintainability, and bringing more cluttered features may ruin UX and people will consider that it's better to use original app than this buggy mod. We need less features.

**Pull request merged**
