### PR TITLE
feat(YouTube - Translations): Update Spanish

### PR DESCRIPTION
**Pull request by FredMan95**
- Added the missing strings.
Note: all current strings in updated-strings.xml have been added.

### CODE REVIEW

**Comment by anddea** [comment]
Thank you. I'll delete updated strings. You can delete all lines from it if you want, it should delete it. 

Also, there is my mistake, there should be no `\nwatching -> views`. So don't add it in translation here:

```xml
<string name="revanced_hide_video_with_low_view_num_multiplier_value">K -> 1 000\nM -> 1 000 000\nB -> 1 000 000 000\nvisualizaciones -> views\nusuarios -> views</string>
```

Can you test this new setting for hiding videos based on views? I checked Spanish and it shows "M de visualizaciones" in feed, so it gotta be `M de -> 1 000 000`.

**Comment by anddea** [comment]
It's fine. For now I see one issue but I'll fix it myself so you don't have to. 

But if you'd like to know, there's a space in the multiline string. It means there will be unneeded space in settngs. Because everything between double quotes "" are going to be detected literally.

```xml
    <string>"multi
    line"</string>
```

So it should be like this
```xml
    <string>"multi
line"</string>
```

**Comment by anddea** [comment]
I've updated some strings for better clarification, please update them as well. If it's fine for your language as it is right now, let me know.

```xml
<string name="revanced_hide_video_with_low_view_num_multiplier_summary">Specify your language template for the number of views shown under each video in the user interface. Each key (a letter/word in your language) -> value (meaning of the key) must be on a new line. Keys go before "->" sign. If you switch app or system language you have to reset this setting.\n\nExamples:\nEnglish: 10K views = K -> 1000, views -> views\nSpanish: 10 K vistas = K -> 1000, vistas -> views</string>
<string name="revanced_hide_video_with_low_view_old_summary">"Hide videos with less than 1,000 views exposed to the home feed.
Some videos, including those from channels you subscribe to, may not be hidden even if they have fewer than 1,000 views.

It's an old version, if you're using option above, you don't need to use this one."</string>
<string name="revanced_hide_video_with_low_view_old_title">[Old] Hide videos with low views</string>
```

**Comment by FredMan95** [comment]
Done

**Pull request merged**
