### PR TITLE
feat(YouTube - Branding): Added a new splash animation for all 3 Revancify icons

### PR DESCRIPTION
**Pull request by Xisrr1**
Edit: All Revancify icons are now included.

### CODE REVIEW

**Review by Francesco146 — APPROVED** [review]

**Comment by Xisrr1** [comment]
I think it's ready

**Comment by Xisrr1** [comment]
> seems good, let @anddea have the final look and it's good to go in a pre-release. good job!

Thanks!

**Comment by anddea** [comment]
Thank you, guys, for collaborating and contributing to this project.

**Comment by decipher3114** [comment]
@Xisrr1, May I know what tool did you use to animate the svg.
Is it shapeshifter or something else?

**Comment by Xisrr1** [comment]
> @Xisrr1, May I know what tool did you use to animate the svg.
> Is it shapeshifter or something else?

ShapeShifter

**Comment by Xisrr1** [comment]
@decipher3114 The animation gets cut in the splash screen, do you have any helpful info on how to fix it?

**Comment by decipher3114** [comment]
prolly, bcz the older splash screen still exists

**Comment by Xisrr1** [comment]
Well, is there any workaround?

**Comment by decipher3114** [comment]
thats something @anddea have to work on...

I am trying to do some modifications to icons and the splash. Hope it goes in the right direction.

**Comment by decipher3114** [comment]
I just checked multiple apps, and found out that all of them cuts the animation once the app is in the Background. So, nothing can we do...

**Comment by Xisrr1** [comment]
> I just checked multiple apps, and found out that all of them cuts the animation once the app is in the Background. So, nothing can we do...

Elaborate?

**Comment by decipher3114** [comment]
I think, on a cold start the splash is terminated early. That's why it happens.
Either make the spash anim shorter or cope 😁

**Comment by Xisrr1** [comment]
That's not the cut I was talking about, but good day to you too! 😄

**Comment by decipher3114** [comment]
> That's not the cut I was talking about, but good day to you too! 😄

Then which one??

**Comment by Xisrr1** [comment]
The Yellow play icon

https://github.com/anddea/revanced-patches/assets/133952156/7dfbe847-2ce5-4890-9ef5-60935b80c601

**Comment by decipher3114** [comment]
Ahh, I guess you haven't read the guidelines. Everything must be inside 200 dp radius.

**Pull request merged**
