### PR TITLE
feat(YouTube & Music - Branding): updated `Revancify Yellow` icon 

### PR DESCRIPTION
**Pull request by Xisrr1**
To-do:

- [x] Make sure the updated launcher icon looks normal. (YT)
- [x] Make sure the updated launcher icon looks normal. (YTM)
- [ ] Update splash screen files. (YT)
- [ ] Update splash screen files. (YTM)
- [x] Replace all header files with new, high-resolution images. (YT)
- [x] Replace all header files with new, high-resolution images. (YTM)

### CODE REVIEW

**Comment by Xisrr1** [comment]
Is the icon too big?

**Comment by anddea** [comment]
> Is the icon too big?

The first one is good.

**Comment by Xisrr1** [comment]
> > Is the icon too big?
> 
> The first one is good.
> 
> I don't like the white bold outline of original icon, the first icon looks fresh and modern.

About the header, how do I connect the icon and the header text for the header files?
I previously drew above the current ones, but I'm now replacing everything with sharper and more colorful icons.

**Comment by anddea** [comment]
Headers are just images, both icon and text are just an image file.

**Comment by Xisrr1** [comment]
> Headers are just images, both icon and text are just an image file. 

I know, I only have the icon, not the wordmark. How do I put the icon and the wordmark in the same image?

**Comment by Xisrr1** [comment]
I have an issue. The splash screen doesn't have a black outline like Revancify blue.

**Comment by anddea** [comment]
> How do I put the icon and the wordmark in the same image?

Use any image editing tool, there are plenty of them, just Google them.

**Comment by Xisrr1** [comment]
> Use any image editing tool, there are plenty of them, just Google them. 

Should I edit the ones from the other icons and put it (the yellow) above? I have no idea where to get the YouTube Wordmark image.

**Comment by anddea** [comment]
You can crop from existing ones

**Comment by Xisrr1** [comment]
> You can crop from existing ones

👍. What about the splash screen issue?

**Comment by anddea** [comment]
We don't need any outlines, the icon itself looks good. You can just make black circle background bigger. These things are better to ask from community in the group, so people collectively decide what's better.

**Comment by Xisrr1** [comment]
I couldn't fix the splash issue. Splash screen does not work.

**Comment by Xisrr1** [comment]
@Francesco146, can you review this?

**Comment by Francesco146** [comment]
what is not working in the splash screen

**Comment by Xisrr1** [comment]
> what is not working in the splash screen

The custom splash screen, it basically uses the app icon as the splash screen, instead if what is put in the splash folder, which doesn't look very good. The other Revancify icons have that as well, I don't think the icon should be delayed for that.

**Comment by Francesco146** [comment]
#725 should fix the splash animation, when i merge it, i'll this this pr. few things changed and it should be easier to edit the brandings in the future

**Comment by Xisrr1** [comment]
> #725 should fix the splash animation, when i merge it, i'll this this pr. few things changed and it should be easier to edit the brandings in the future

You mean splash screen?

**Comment by Francesco146** [comment]
yes sry

**Pull request merged**
