### PR TITLE
 Updated-strings.xml

### PR DESCRIPTION
**Pull request by UnMarshmallow**
French language.

### CODE REVIEW

**Comment by anddea** [comment]
Hello. Are you going to translate other strings as well, or should I merge it now?

**Comment by UnMarshmallow** [comment]
I'll continue later, no need to merge now ^^

**Comment by UnMarshmallow** [comment]
If I made a mistake somewhere, I apologize.

**Comment by UnMarshmallow** [comment]
I'm sorry but I have a problem... I want to update the "dev" branch with the new updates but I can't. The "main" branch has the Sync function but not the "dev" branch. How can I do ? (Sorry, I'm new to Github.)

**Pull request closed without merging**
