### PR TITLE
feat(YouTube - Translations): Update Chinese Simplified

### PR DESCRIPTION
**Pull request by re-zero001**
I think my translation is not bad now.And I build it with no problem.Now there are only two English strings I can't find the name.About inotia00's Crowdin，I don't know how to upload the file to that website,I will try to do that.

### CODE REVIEW

**Comment by re-zero001** [comment]
I found a new wrong.Wait me.

**Comment by re-zero001** [comment]
I will most likely not modify it again.I built it to apk and module,it works fine.

**Comment by anddea** [comment]
There are conflicts with dev branch, please resolve conflicts or reopen again with your new file

**Comment by anddea** [comment]
You can change here to main branch, copy change to dev branch, paste it. Verify that your translation is relevant for dev too.

**Comment by re-zero001** [comment]
I translated the strings in [2.225.0-dev.11](https://github.com/anddea/revanced-patches/compare/v2.225.0-dev.10...v2.225.0-dev.11) .I didn't know how to fork dev branch before.

**Pull request closed without merging**
