### PR TITLE
feat: Merge v4.13.1-dev.3

### PR DESCRIPTION
**Pull request by Francesco146**
ref: https://github.com/anddea/revanced-integrations/pull/28

### CODE REVIEW

**Comment by Francesco146** [comment]
@anddea wait until i cherry pick the latest changes, then i'll take a break from this, i want to tell everyone that, i won't stop making patches, i'll continue on my repo and port my changes here and in rvx

**Comment by anddea** [comment]
> wait until i cherry pick the latest changes

Sure, any ETA when are you going to do that?

**Comment by Francesco146** [comment]
i just need the push access to this branch, I've already cherry picked :)

**Comment by vippium** [comment]
Merging 4.13.1 dev-3 (includes some fixes)

**Pull request merged**
